{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-neoforge",
    "version": "1.21-2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-neoforge",
          "version": {
            "requires": "1.21-1.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.0.3.jar",
          "url": "fastconfigapi-neoforge-1.21-2.0.3.jar",
          "size": 106820,
          "sha512": "3a9fb5e550c0a22c1cc8ed8929fb95d4849c06689221df95aa366a24b1115d5f5ad35a6d90e1b5991c947d71b1b3d6bcb57e4b6a98cb52b5a407eaa3eaf1a166",
          "sha256": "a20f8efbdf2415ea7ce99d6f10d28f93c022e2f4c47cce12abe33b38f1845a93",
          "sha1": "984451ac80b95b382c2a732713bbc50095e8497f",
          "md5": "2d0d61f1ef25785bd3dcbd5d01bfff46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-neoforge",
          "version": {
            "requires": "1.21-1.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.0.3.jar",
          "url": "fastconfigapi-neoforge-1.21-2.0.3.jar",
          "size": 106820,
          "sha512": "3a9fb5e550c0a22c1cc8ed8929fb95d4849c06689221df95aa366a24b1115d5f5ad35a6d90e1b5991c947d71b1b3d6bcb57e4b6a98cb52b5a407eaa3eaf1a166",
          "sha256": "a20f8efbdf2415ea7ce99d6f10d28f93c022e2f4c47cce12abe33b38f1845a93",
          "sha1": "984451ac80b95b382c2a732713bbc50095e8497f",
          "md5": "2d0d61f1ef25785bd3dcbd5d01bfff46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.0.3-sources.jar",
          "url": "fastconfigapi-neoforge-1.21-2.0.3-sources.jar",
          "size": 4488,
          "sha512": "2c284883a97edb5646fb18cc94e66100a9437a585916e8d1a03ee20c70e156c082b965f90f0f1bea40414cc04e738dc32def7a46847a5eece4f76d0d5f4fb83f",
          "sha256": "dec5b39f38727fa0d5232d98ea4219735bdd5830ed8ab9b757c5d298785dde3d",
          "sha1": "721d460b90ac40e9f24686229e3a6bd6f00b33ce",
          "md5": "b2961dcc2ba3e8b6c9dbef5a16bd1e49"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.0.3-dev-shadow.jar",
          "url": "fastconfigapi-neoforge-1.21-2.0.3-dev-shadow.jar",
          "size": 47882,
          "sha512": "f9850a8094540c7eb00b3f4fe49d0af02eae24539b7cf1dd87d03e79ba4e4b2fc8f8c264c53e51f3be9625b751b04a60d1989e4c2bed596a63b3f52f6cc61cb3",
          "sha256": "3a80741c7aa4fbcd24117d1f730697035f4db11c68b5fd6d0dd188524b4bb58d",
          "sha1": "842aee5fdc248662eb6c8ab7b49d7b08891e19cb",
          "md5": "8e7a08150b7d14c445af84dbcfc7e708"
        }
      ]
    }
  ]
}
