{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "1.19.3-1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.19.3-1.0.1.jar",
          "url": "fastconfigapi-common-1.19.3-1.0.1.jar",
          "size": 6905,
          "sha512": "f3da7b3c3064a7e3bfe7043caf321d9fa3b273e7b101159d201a49e2e37164f8cbeb129871dd7ad6eec3a4f25a97c1e03c7dd5970027d0bc9d1d784c471c8e03",
          "sha256": "cf1f10c29413467c0abef6177a73877d7c48ad8c56bb67c8b49863923c37aef3",
          "sha1": "aad97a91ff61a1a17b271ad7c6e3e46b0459035a",
          "md5": "61fc4e0abb8aa9e67b45de297cc0fa7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-1.19.3-1.0.1.jar",
          "url": "fastconfigapi-common-1.19.3-1.0.1.jar",
          "size": 6905,
          "sha512": "f3da7b3c3064a7e3bfe7043caf321d9fa3b273e7b101159d201a49e2e37164f8cbeb129871dd7ad6eec3a4f25a97c1e03c7dd5970027d0bc9d1d784c471c8e03",
          "sha256": "cf1f10c29413467c0abef6177a73877d7c48ad8c56bb67c8b49863923c37aef3",
          "sha1": "aad97a91ff61a1a17b271ad7c6e3e46b0459035a",
          "md5": "61fc4e0abb8aa9e67b45de297cc0fa7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.19.3-1.0.1-sources.jar",
          "url": "fastconfigapi-common-1.19.3-1.0.1-sources.jar",
          "size": 5202,
          "sha512": "08dd5bfe07a371463290bbd33a0b34bf3c0103d11b536b4a70e7f1800cefc3fa9638fe5463b13c35272c12723fafccd6c2defb1992e69f716e0ffc9c4a4f9aa4",
          "sha256": "5f714b8b968ac6fdc0f4258bc035abec73cb4f75449219a00176f40cbaf711dc",
          "sha1": "40f9e46e67df396caea318ae0c9451132030de87",
          "md5": "fdd3b2f3f421a437ef91ec2d89f02a20"
        }
      ]
    }
  ]
}
