{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.void_lib",
    "module": "void_lib-fabric",
    "version": "1.21.8-1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.0+1.21.8"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "17.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "void_lib-fabric-1.21.8-1.1.6.jar",
          "url": "void_lib-fabric-1.21.8-1.1.6.jar",
          "size": 264914,
          "sha512": "af1b45fa819e0681edaa05cdf11cf2ce3a2819fd5231576bbea004232433c03f4ce2ca4866499c23ac9bdf819eb75c6cc02bb0ce8b2cf6d1220ca516e597af84",
          "sha256": "1bae149536ca9badcddce55e54b8d980e931d184fb23b8ac2bd52659685d362d",
          "sha1": "1b18f01b9105ae6c5804f42cd61acf20a2dbf1e0",
          "md5": "c3dc985c2eccbd73c4ed09a3d9b82207"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.0+1.21.8"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "17.0.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "void_lib-fabric-1.21.8-1.1.6.jar",
          "url": "void_lib-fabric-1.21.8-1.1.6.jar",
          "size": 264914,
          "sha512": "af1b45fa819e0681edaa05cdf11cf2ce3a2819fd5231576bbea004232433c03f4ce2ca4866499c23ac9bdf819eb75c6cc02bb0ce8b2cf6d1220ca516e597af84",
          "sha256": "1bae149536ca9badcddce55e54b8d980e931d184fb23b8ac2bd52659685d362d",
          "sha1": "1b18f01b9105ae6c5804f42cd61acf20a2dbf1e0",
          "md5": "c3dc985c2eccbd73c4ed09a3d9b82207"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "void_lib-fabric-1.21.8-1.1.6-sources.jar",
          "url": "void_lib-fabric-1.21.8-1.1.6-sources.jar",
          "size": 27258,
          "sha512": "4a8bbc6a149ef6c3de87b49e7e907990c828952a6e1f943704f3bbfb30f908c644afcec7390bdf36b3458d39708c6bd0e15b7df119ced911a7253d9581d036ee",
          "sha256": "9bde098e2853a34247efad342628986af1130c1ff87a7f242a10ff11a7bf6a7c",
          "sha1": "ee2e586e57f4d345f3aa11a5e55d592462ba2c94",
          "md5": "1d462a134dce58adb3c9a488e2f37e0e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "void_lib-fabric-1.21.8-1.1.6-dev-shadow.jar",
          "url": "void_lib-fabric-1.21.8-1.1.6-dev-shadow.jar",
          "size": 263405,
          "sha512": "817871d16282ba59cb715f26c50535f2e62669d7531010cc6b01e2263caf64a3a7d61ca5c10c44df067094143e634fe9298c06d479796435082912ad57f63b45",
          "sha256": "fe27a314ceaca9ecb5dc100408afcb75d81fb8e433a9e7a30eb0b33a61b5e598",
          "sha1": "c550ddbc646f568f5a7c61d17abc85f20e47ab14",
          "md5": "499bf9b9a8052959d870d89996d0d6b9"
        }
      ]
    }
  ]
}
