{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-forge",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-forge-1.0.1.jar",
          "url": "fastconfigapi-forge-1.0.1.jar",
          "size": 262625,
          "sha512": "d9efd97a768559199df67efd72535cdbd8f2b3289d6ab4cc4fec196acabc40906a375ee6adddd67f79532f0f141ec9e7ddc7b761d3ce59f68d43ae1b18c4c88b",
          "sha256": "74cac28f88e1245f9dac4b207fb98501b14c1b55faa42f7bc5ba6c34780341bc",
          "sha1": "795ac10d01bc5138b8df79b26c46e7f56eb020ab",
          "md5": "5c98ec506747cdaf19b13f334b07e837"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-forge-1.0.1.jar",
          "url": "fastconfigapi-forge-1.0.1.jar",
          "size": 262625,
          "sha512": "d9efd97a768559199df67efd72535cdbd8f2b3289d6ab4cc4fec196acabc40906a375ee6adddd67f79532f0f141ec9e7ddc7b761d3ce59f68d43ae1b18c4c88b",
          "sha256": "74cac28f88e1245f9dac4b207fb98501b14c1b55faa42f7bc5ba6c34780341bc",
          "sha1": "795ac10d01bc5138b8df79b26c46e7f56eb020ab",
          "md5": "5c98ec506747cdaf19b13f334b07e837"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-forge-1.0.1-sources.jar",
          "url": "fastconfigapi-forge-1.0.1-sources.jar",
          "size": 261010,
          "sha512": "19eb55de688a878bf42231937a7409ec3a21ae9cb0ed58cd749f8ebcc1f9793a21cba95ba5854d687449fc2dd33a6f29d17879d18dad9a8a94fd0d98cded7b52",
          "sha256": "e0e5bd751d2a58c9cdf0eb7146a6ffb7367d7dfd5ba25105c00ee546f328b648",
          "sha1": "16a74917fce012844b25230683be2d02649f1b4f",
          "md5": "07f436de5991444ebc61fc9692d1f89c"
        }
      ]
    }
  ]
}
