{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-fabric",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-fabric-1.0.1.jar",
          "url": "fastconfigapi-fabric-1.0.1.jar",
          "size": 262628,
          "sha512": "5a333e150c612c1a4a6d925678c9234fae99e44266705d4d29d1dfbc7ab5e7d3444f0539e33f7f2b0fd8a1d8e62893ec9c0da6c295f6212849002e6037f0cdcc",
          "sha256": "db8a492c2dc2c1e2c62d4e9ba686ccd4ef7e9ea71b4ddbe698ccc844356a085f",
          "sha1": "fdf37030605d631920636897baeb768b62baccf5",
          "md5": "469ace5c3901c75c2f97076815ab7b52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-fabric-1.0.1.jar",
          "url": "fastconfigapi-fabric-1.0.1.jar",
          "size": 262628,
          "sha512": "5a333e150c612c1a4a6d925678c9234fae99e44266705d4d29d1dfbc7ab5e7d3444f0539e33f7f2b0fd8a1d8e62893ec9c0da6c295f6212849002e6037f0cdcc",
          "sha256": "db8a492c2dc2c1e2c62d4e9ba686ccd4ef7e9ea71b4ddbe698ccc844356a085f",
          "sha1": "fdf37030605d631920636897baeb768b62baccf5",
          "md5": "469ace5c3901c75c2f97076815ab7b52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-fabric-1.0.1-sources.jar",
          "url": "fastconfigapi-fabric-1.0.1-sources.jar",
          "size": 260754,
          "sha512": "5e49126e733641f89c297fa86c070ad5a1572d7eae9debd86a5bf808a9a76309e542020b73d8846038890843cedc3bf1db9695a5ba8f12f5ae024e16a9996d2d",
          "sha256": "3e70ee70a6cc5f975cbff334b40bb7826cb9e709a23c56a6749e1c8355822b40",
          "sha1": "81266c1b732c9f9325cea74d21ee325664297d94",
          "md5": "9822d2b930932de3ff599b05c5cf7aa7"
        }
      ]
    }
  ]
}
