{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-neoforge",
    "version": "1.21-2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-neoforge",
          "version": {
            "requires": "1.21-1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.1.0.jar",
          "url": "fastconfigapi-neoforge-1.21-2.1.0.jar",
          "size": 108376,
          "sha512": "82c6565e091efddd5170ed020345cd839c6dd2d21a1e40239c577cc72c9de65af24f114985bce87b1f7af2ec80e5977cc6d20a8ddc33fb293111b2003ffce934",
          "sha256": "a30c92c76ec879b7f0dc4313a74cd52135ac2cd7193bedd0eec6bd84df41f1f2",
          "sha1": "4278e54faa613ad7cab06eab08e5d052120a38a0",
          "md5": "7859b4004dcc0e80afd68bda395c27fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-neoforge",
          "version": {
            "requires": "1.21-1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.1.0.jar",
          "url": "fastconfigapi-neoforge-1.21-2.1.0.jar",
          "size": 108376,
          "sha512": "82c6565e091efddd5170ed020345cd839c6dd2d21a1e40239c577cc72c9de65af24f114985bce87b1f7af2ec80e5977cc6d20a8ddc33fb293111b2003ffce934",
          "sha256": "a30c92c76ec879b7f0dc4313a74cd52135ac2cd7193bedd0eec6bd84df41f1f2",
          "sha1": "4278e54faa613ad7cab06eab08e5d052120a38a0",
          "md5": "7859b4004dcc0e80afd68bda395c27fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.1.0-sources.jar",
          "url": "fastconfigapi-neoforge-1.21-2.1.0-sources.jar",
          "size": 4578,
          "sha512": "c47692ebdd396128a98f7c605a27e8106f131f53246ec4e5e945864a964388a4fa2c7bfc2fea3fb75fbe29b6d69c8e17eaae1a368d5a7ba78cbcec17a5d49081",
          "sha256": "83d86ea4dbae7ae5642440bc914c2bf02136d57d2a08d26a1c174c4457c72f1d",
          "sha1": "f766c3a6ccfc21775e29683bf8740304ef0315ed",
          "md5": "39f7e8f34aab079961fc708a959eab9c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21-2.1.0-dev-shadow.jar",
          "url": "fastconfigapi-neoforge-1.21-2.1.0-dev-shadow.jar",
          "size": 49298,
          "sha512": "44c517f02bbdef68bdfff27bfe7028e05e888e9df96ab60d5ef3eab073d3c82fe9df827a0636589ce140c55f8b10bbdf48115ad9fcfa311f87870d89d8181c54",
          "sha256": "0df2af742e774a0e609a4171629c379c6f9e0b4aea90093dee45e0e2a6c7cbfd",
          "sha1": "4c7e7a93ec87af0b9934dbfb2dab9cae1b2bf69c",
          "md5": "11f54a7850c018d12e2e6904a294b908"
        }
      ]
    }
  ]
}
