{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "1.19.2-1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.19.2-1.0.1.jar",
          "url": "fastconfigapi-common-1.19.2-1.0.1.jar",
          "size": 261249,
          "sha512": "b69d8bdf229bee40278bae282260c8bd2274067f5cd58ed6584b69ccc48ab0e8f83824a17c62bdd5857fc14fa4028885f34cc491dd46aab3dbd21ddae2d029b4",
          "sha256": "d553e2a26f81aa80630bcf2c1864b958e4c7aac0e275a50d9a75767469704ea4",
          "sha1": "4e643664d037fe3af635979db7906b51fc818eb4",
          "md5": "40c9b9383dc157de89b92c4008076606"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-1.19.2-1.0.1.jar",
          "url": "fastconfigapi-common-1.19.2-1.0.1.jar",
          "size": 261249,
          "sha512": "b69d8bdf229bee40278bae282260c8bd2274067f5cd58ed6584b69ccc48ab0e8f83824a17c62bdd5857fc14fa4028885f34cc491dd46aab3dbd21ddae2d029b4",
          "sha256": "d553e2a26f81aa80630bcf2c1864b958e4c7aac0e275a50d9a75767469704ea4",
          "sha1": "4e643664d037fe3af635979db7906b51fc818eb4",
          "md5": "40c9b9383dc157de89b92c4008076606"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.19.2-1.0.1-sources.jar",
          "url": "fastconfigapi-common-1.19.2-1.0.1-sources.jar",
          "size": 259612,
          "sha512": "3cd3bda955f8563305f07c01323adbd5fc94d502805984fd42d5c65899e59f331cadd31ac57992bbd2da26fc603d4d494337b019be9781bf38a3b004a71b02d0",
          "sha256": "84799cc0fbd47504de4879a5aff02523fc1bdd7b24a0635de2c62875bfa02a0e",
          "sha1": "7d522579258cd03b21cf71601ea259a4da0e5330",
          "md5": "b21f8c975232cc955ab43aa86b63f4f1"
        }
      ]
    }
  ]
}
