{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.1.0.jar",
          "url": "fastconfigapi-common-1.1.0.jar",
          "size": 260058,
          "sha512": "93886135615fea6b8026b50a6afc3e64af61128b27a1a5dc70bb4496daf008698d4f718f714a3fa1e10409b625fded0b7ed5dd9f91b814870aa4b3c692118133",
          "sha256": "20c0c65f28159c6f02e916acd594d6d52a1684694ff10d27c8d41a40f3df8b64",
          "sha1": "8886bdd623ae23183c1fd3901e5aaf58ad96f7a1",
          "md5": "29d79d6a59ca833308d9361280bf1c47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-1.1.0.jar",
          "url": "fastconfigapi-common-1.1.0.jar",
          "size": 260058,
          "sha512": "93886135615fea6b8026b50a6afc3e64af61128b27a1a5dc70bb4496daf008698d4f718f714a3fa1e10409b625fded0b7ed5dd9f91b814870aa4b3c692118133",
          "sha256": "20c0c65f28159c6f02e916acd594d6d52a1684694ff10d27c8d41a40f3df8b64",
          "sha1": "8886bdd623ae23183c1fd3901e5aaf58ad96f7a1",
          "md5": "29d79d6a59ca833308d9361280bf1c47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.1.0-sources.jar",
          "url": "fastconfigapi-common-1.1.0-sources.jar",
          "size": 259032,
          "sha512": "7757b3aab8b8f719339703f047597e00598d7119ec526c25804b870d20973f782408b4a1ea97487082e4f44213799afa1e50fd5b3a552122889fd2fac77b123c",
          "sha256": "8f28390cc12ea358ad58b0500c8425ca454af882c76a6a48888253152d1ab10e",
          "sha1": "b8b6ef107536b771679fd21a7603ee2712370c3a",
          "md5": "b76d8c085fc19a020ac762ac11b0a3af"
        }
      ]
    }
  ]
}
