{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.1.0.jar",
          "url": "fastconfigapi-common-1.1.0.jar",
          "size": 260058,
          "sha512": "05a8b4fbd7ff423e7577d86bb55b2103db0c3e69e6d7d2508b34ea9f3789a13220d4df8bc8dbe7f8ab7027e6e94c3e57477234d456498e9ddfeabde58ea3556d",
          "sha256": "6cf18bc25b1b795184f93353bd0ba879323042b53c60f33c0a85f4429f3c98e8",
          "sha1": "6158156b05035c1d7798a5792ad947db92f493bd",
          "md5": "a77ca5ced1daa45b727a46c5940f747e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-1.1.0.jar",
          "url": "fastconfigapi-common-1.1.0.jar",
          "size": 260058,
          "sha512": "05a8b4fbd7ff423e7577d86bb55b2103db0c3e69e6d7d2508b34ea9f3789a13220d4df8bc8dbe7f8ab7027e6e94c3e57477234d456498e9ddfeabde58ea3556d",
          "sha256": "6cf18bc25b1b795184f93353bd0ba879323042b53c60f33c0a85f4429f3c98e8",
          "sha1": "6158156b05035c1d7798a5792ad947db92f493bd",
          "md5": "a77ca5ced1daa45b727a46c5940f747e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-1.1.0-sources.jar",
          "url": "fastconfigapi-common-1.1.0-sources.jar",
          "size": 259032,
          "sha512": "d923bb827d22bb9b0c74447968c79ab1b99bfebe98f33e68339214258aaa41539acb53fc49acb5e520d753a7ea66583fe274fb594fdb400102d42c44238b9b69",
          "sha256": "39539d16d37d4ca648954aafa8bfca33f821db181314ba6fd96c287debf5621f",
          "sha1": "f2de6b1b4a7b5acfb7fef8bf3c64af714a6a37bc",
          "md5": "c749eb34b819892a8386876064507e93"
        }
      ]
    }
  ]
}
