{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0.jar",
          "url": "fastconfigapi-common-2.1.0.jar",
          "size": 28873,
          "sha512": "e60471d3c59b4655d0f1eaf9947cc5391fa9b67036a0152a86324b9c797010839a82c9d0d9588686a445502291f8caf7ef6d3a39d8c04e1ad09b170def8b5184",
          "sha256": "601ab8e44625d202dbedf714e79b9ddef4757eaa53b7272e643c1e9fc3b70ba0",
          "sha1": "bdb19953304e3119f6900f71e3af1d0230b365a0",
          "md5": "17844a33a45bc6de9b98f8f3f3ea4261"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0.jar",
          "url": "fastconfigapi-common-2.1.0.jar",
          "size": 28873,
          "sha512": "e60471d3c59b4655d0f1eaf9947cc5391fa9b67036a0152a86324b9c797010839a82c9d0d9588686a445502291f8caf7ef6d3a39d8c04e1ad09b170def8b5184",
          "sha256": "601ab8e44625d202dbedf714e79b9ddef4757eaa53b7272e643c1e9fc3b70ba0",
          "sha1": "bdb19953304e3119f6900f71e3af1d0230b365a0",
          "md5": "17844a33a45bc6de9b98f8f3f3ea4261"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0-sources.jar",
          "url": "fastconfigapi-common-2.1.0-sources.jar",
          "size": 18241,
          "sha512": "3f90a61719fd3fad30d9aa5fae4ddb936b264d7b21f6571b7af009d397aa162edc948d04f4bd80e9224fe01608d51f48e02a652edadb1c175e19ee556cc9a77b",
          "sha256": "90c8e2b09c23f7783a9a574591935ff27940390b9b6af7781cac74d14ce40b69",
          "sha1": "d6e4e6b96fc210eb14aaae1e565e40169df23fa0",
          "md5": "56c34da7d137b6486fdce883a2a2fb2c"
        }
      ]
    }
  ]
}
