{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0.jar",
          "url": "fastconfigapi-common-2.1.0.jar",
          "size": 42799,
          "sha512": "2bdf39e52b3feccde797aab388dec105f4b1ae2b53128a1075db8f52435ad6566b43e7cbcecb01601ccf145368a17d066ae2aa4000608cd6ab026610df856aa6",
          "sha256": "bda5a46ea1299b432dc27de5ddd070953cfd3561ea5c4da01b5be3ff05bcd70a",
          "sha1": "9e5ec13f75ae41e11f3c7424e4c3fbfa91e2b03a",
          "md5": "fea54e75bdf05daa69ae4bf3cb8d9ceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0.jar",
          "url": "fastconfigapi-common-2.1.0.jar",
          "size": 42799,
          "sha512": "2bdf39e52b3feccde797aab388dec105f4b1ae2b53128a1075db8f52435ad6566b43e7cbcecb01601ccf145368a17d066ae2aa4000608cd6ab026610df856aa6",
          "sha256": "bda5a46ea1299b432dc27de5ddd070953cfd3561ea5c4da01b5be3ff05bcd70a",
          "sha1": "9e5ec13f75ae41e11f3c7424e4c3fbfa91e2b03a",
          "md5": "fea54e75bdf05daa69ae4bf3cb8d9ceb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0-sources.jar",
          "url": "fastconfigapi-common-2.1.0-sources.jar",
          "size": 31510,
          "sha512": "0859e7441ab90613a2f081ff7b71e97b91a8176667c9f9bb9ccc333c8e66b2b18fd70ba25faa1f24f32f41e3defecfa5d4923d2ce8d08ec1f3c93f892e3abacf",
          "sha256": "d9813e004b534a1df3e2e6308fbc94f12c13e503fd7c5ff00c0826f1aee39450",
          "sha1": "35edde441f45cddfdfa35eb8a3bafd2dba19e033",
          "md5": "f07958e9b4da4100e2fae1ccf12bf1ab"
        }
      ]
    }
  ]
}
