{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0.jar",
          "url": "fastconfigapi-common-2.1.0.jar",
          "size": 41456,
          "sha512": "3b9fb58e371f0d4b5887a876f7fe51d12311c10aa7871ab212c08a5e7e6948eb115a38cf16c6625326570307932bf76b9c895e74979a08bd317e25538cbcab34",
          "sha256": "bcfb51767b182fe48412c313e9bc6bb9e18b16a5bea95fafdda87bb6e876de4a",
          "sha1": "b7df26516046aa623cf19c91db8b1d9e1184f629",
          "md5": "789d77c543d92e2cfc8beb77d96a755c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0.jar",
          "url": "fastconfigapi-common-2.1.0.jar",
          "size": 41456,
          "sha512": "3b9fb58e371f0d4b5887a876f7fe51d12311c10aa7871ab212c08a5e7e6948eb115a38cf16c6625326570307932bf76b9c895e74979a08bd317e25538cbcab34",
          "sha256": "bcfb51767b182fe48412c313e9bc6bb9e18b16a5bea95fafdda87bb6e876de4a",
          "sha1": "b7df26516046aa623cf19c91db8b1d9e1184f629",
          "md5": "789d77c543d92e2cfc8beb77d96a755c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.0-sources.jar",
          "url": "fastconfigapi-common-2.1.0-sources.jar",
          "size": 31293,
          "sha512": "c5647d205d7ba96a580628824caa7fc54b5ab5a61855857aabfadbe02277d00ae637ca14d86016011ebe2aaec13157c4565c072eb1ecb09e185533f87e450034",
          "sha256": "66ea362241ee505bed8d7d42d557a2bf693bbb0d27bd344ef294d25835708bcc",
          "sha1": "a8a4d78395e71d0dec2483d72fc3947738ed4f73",
          "md5": "f2313a83df79bf1c60609b71a14a5cd7"
        }
      ]
    }
  ]
}
