{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-fabric",
    "version": "1.21-2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-fabric",
          "version": {
            "requires": "1.21-1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-fabric-1.21-2.1.0.jar",
          "url": "fastconfigapi-fabric-1.21-2.1.0.jar",
          "size": 105344,
          "sha512": "c5a06d662ef41bb341c9861b43d73b8e49f4573e61e4534f3045e70350e5692d028e1585ea91c1ec2da08d838874415f3249193c0c07e0415f20370d8dce6f52",
          "sha256": "ed540d3b4a8a34777f3bb1b7ab426e90429c0d333302adec874e13b7d9ca0460",
          "sha1": "3d7010027743307302afd241104fee0cec722dc7",
          "md5": "187fd6571ace05b76ba4be249f96dc7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-fabric",
          "version": {
            "requires": "1.21-1.1.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-fabric-1.21-2.1.0.jar",
          "url": "fastconfigapi-fabric-1.21-2.1.0.jar",
          "size": 105344,
          "sha512": "c5a06d662ef41bb341c9861b43d73b8e49f4573e61e4534f3045e70350e5692d028e1585ea91c1ec2da08d838874415f3249193c0c07e0415f20370d8dce6f52",
          "sha256": "ed540d3b4a8a34777f3bb1b7ab426e90429c0d333302adec874e13b7d9ca0460",
          "sha1": "3d7010027743307302afd241104fee0cec722dc7",
          "md5": "187fd6571ace05b76ba4be249f96dc7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-fabric-1.21-2.1.0-sources.jar",
          "url": "fastconfigapi-fabric-1.21-2.1.0-sources.jar",
          "size": 4627,
          "sha512": "2b22dfd14752d0b0352a005f7f6a90e004da7bd43b7633e5927e636b7a01fe3e237c4f59dea3fc2767fbeafae8e10db27fc34c274b4eb6b3cc95164424310b1b",
          "sha256": "2440b7fb1116b9385425df8cca76c6f8cccb61f7db40ba3eb516ad66b0cccd9b",
          "sha1": "1eaef64d8438409bd90d564346b619dfec012517",
          "md5": "4ab46e3a7b66ac46ee637d3e5a0a1066"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-fabric-1.21-2.1.0-dev-shadow.jar",
          "url": "fastconfigapi-fabric-1.21-2.1.0-dev-shadow.jar",
          "size": 46564,
          "sha512": "f7bb4b22fe9c231f1bb304723eed2464e1df99c15a575d6ade8a330e19d5631c6ed14a5f2d91132d4ff4f1658bb1026203036728e712a784b9c0aef0b1603490",
          "sha256": "3bd399547cd1256d46e904586da7e46268527fa60b5bbd2730e9ac768b31f149",
          "sha1": "3f573490e55f61b6ed635a9ac1d3455ddbeb76c8",
          "md5": "23ee8788280c03b5fdd93ab5c5b89840"
        }
      ]
    }
  ]
}
