{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-fabric",
    "version": "1.20.1-2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-fabric",
          "version": {
            "requires": "1.20.1-1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-fabric-1.20.1-2.1.2.jar",
          "url": "fastconfigapi-fabric-1.20.1-2.1.2.jar",
          "size": 107546,
          "sha512": "46ee06a572b4cc58156863d471dd2fcdb6bdae4526e0416c8d0dd2392f811a9d65a7902c4cd1273d536bd1dd4045e0a0dd547222e1773631ad058ca6471d8c05",
          "sha256": "210a0c02674ac94c7815cc24c066f0ede1390b814126de669b64ef7db111a68c",
          "sha1": "0ace6999366ad3c4ff563948b70ee2182d1eeab8",
          "md5": "2cede372d383aec3334599ad37ec8cc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-fabric",
          "version": {
            "requires": "1.20.1-1.1.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-fabric-1.20.1-2.1.2.jar",
          "url": "fastconfigapi-fabric-1.20.1-2.1.2.jar",
          "size": 107546,
          "sha512": "46ee06a572b4cc58156863d471dd2fcdb6bdae4526e0416c8d0dd2392f811a9d65a7902c4cd1273d536bd1dd4045e0a0dd547222e1773631ad058ca6471d8c05",
          "sha256": "210a0c02674ac94c7815cc24c066f0ede1390b814126de669b64ef7db111a68c",
          "sha1": "0ace6999366ad3c4ff563948b70ee2182d1eeab8",
          "md5": "2cede372d383aec3334599ad37ec8cc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-fabric-1.20.1-2.1.2-sources.jar",
          "url": "fastconfigapi-fabric-1.20.1-2.1.2-sources.jar",
          "size": 6527,
          "sha512": "038b4eb1c19d8023bc7e8b2a2bdf7daa0769ef3af44a3ae6267f62dd3ec9b169465ef4a394aa95720ce9d08fe4f8e2c96791255b8dc2412a186b5d14f68018d5",
          "sha256": "97a5178298c682e661c32e9823552417ce66f3187effad804e5e98d3a38913ef",
          "sha1": "28b55bbccad983766097fde06d85b52b5886601d",
          "md5": "bbffd7d5532402b81009bb3ebfc9f9da"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-fabric-1.20.1-2.1.2-dev-shadow.jar",
          "url": "fastconfigapi-fabric-1.20.1-2.1.2-dev-shadow.jar",
          "size": 48721,
          "sha512": "b6a4bbc6178405bd68b627fd64e4e8953baf7d052454aedeba515a8a3b6d475c4520a86b82fb5f74ebcd61151c00924961d158d8177fc2bbf6c29f6576e57a49",
          "sha256": "255442f82d45f8faf94b0b9850b4c5d801ef151bc29fd07282fa50c4d74a4bb9",
          "sha1": "347c454e06bec3eb18b9fe4ef221e80a5be10c0a",
          "md5": "fc1f08f6619da5ffaa8547e3156ea804"
        }
      ]
    }
  ]
}
