{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-forge",
    "version": "1.20.1-2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-forge",
          "version": {
            "requires": "1.20.1-1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.0.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.0.jar",
          "size": 276587,
          "sha512": "c0b090ffadaad9052412f4db7603f1e77dae1062001892eb7e2538005e7e1331c84cabd0f4289905c267dbe3b039b915c43b77cae1a3fb7057765f922253c03f",
          "sha256": "f9bc306cb624c8d7e6290571019fb49bb2efa2790a1d6281f3db24e8b32c85f0",
          "sha1": "3a6acdbd3178b37c6df4353598242ac366b02f0f",
          "md5": "b8d2135a796b42a60e6b80f5577ebcad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-forge",
          "version": {
            "requires": "1.20.1-1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.0.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.0.jar",
          "size": 276587,
          "sha512": "c0b090ffadaad9052412f4db7603f1e77dae1062001892eb7e2538005e7e1331c84cabd0f4289905c267dbe3b039b915c43b77cae1a3fb7057765f922253c03f",
          "sha256": "f9bc306cb624c8d7e6290571019fb49bb2efa2790a1d6281f3db24e8b32c85f0",
          "sha1": "3a6acdbd3178b37c6df4353598242ac366b02f0f",
          "md5": "b8d2135a796b42a60e6b80f5577ebcad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.0-sources.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.0-sources.jar",
          "size": 4666,
          "sha512": "8ef7451750e7c6b0fd9f7c4a4d58ba9d2832d9f2264785af23c8bcb631c73fc82a84ecda622364f9cc921a9a00740374efbfddf054e2175e6596b2da3ad77f97",
          "sha256": "4fd01d6024bc0ac7f8213d86a2c2d5d14ed5c20dd8a2abb9321e67fe8e4fcee9",
          "sha1": "f8e00dc4c9bed659f2db4108e5705386dd8f08fc",
          "md5": "ff8745a7ee4c0fc72b9738c91e33faab"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.0-dev-shadow.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.0-dev-shadow.jar",
          "size": 34999,
          "sha512": "fe1b619d6df7447284cc2b8e458161afb2440ee9029f8d51a285d5a0d0cef666df48ae09d8f5b13136185e0aec4ac3b90de8b6f7d8dbeb775ceaf2e6849688a2",
          "sha256": "8da0a5a21ea740fabc75116ab189702c4ffe1714fe92ccb10110237d28533a00",
          "sha1": "c32b3a5f02b7d80820c2c8b2545063cbc5221742",
          "md5": "c002f359cc51e8258479242b9c326a07"
        }
      ]
    }
  ]
}
