{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-neoforge",
    "version": "1.21.4-2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-neoforge",
          "version": {
            "requires": "1.21.4-1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21.4-2.1.0.jar",
          "url": "fastconfigapi-neoforge-1.21.4-2.1.0.jar",
          "size": 108370,
          "sha512": "306804e6458b4f4ba8eca83f88b1f4e850736c0a9ad681259eabff6aaa8bb9f48c1d4c7d5e629682e44484bfae05c152989e644095fb1002bbd43b381a3469fa",
          "sha256": "7a99eead52f972baf1c575b9c534e8e237c2a643cfbf3362e8a55d8e8c9b2bee",
          "sha1": "9dd1541cad4d9ae47624b7a738b5c168da989ef2",
          "md5": "333fd57e86dcc1f95b71ad89452203cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-neoforge",
          "version": {
            "requires": "1.21.4-1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21.4-2.1.0.jar",
          "url": "fastconfigapi-neoforge-1.21.4-2.1.0.jar",
          "size": 108370,
          "sha512": "306804e6458b4f4ba8eca83f88b1f4e850736c0a9ad681259eabff6aaa8bb9f48c1d4c7d5e629682e44484bfae05c152989e644095fb1002bbd43b381a3469fa",
          "sha256": "7a99eead52f972baf1c575b9c534e8e237c2a643cfbf3362e8a55d8e8c9b2bee",
          "sha1": "9dd1541cad4d9ae47624b7a738b5c168da989ef2",
          "md5": "333fd57e86dcc1f95b71ad89452203cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21.4-2.1.0-sources.jar",
          "url": "fastconfigapi-neoforge-1.21.4-2.1.0-sources.jar",
          "size": 4579,
          "sha512": "313ca77f5dfb5833bbb21c86b9f943af2c7e7934ef1ff284c789324b6d2b37286fecfc92e5908f4c27374d76f153fffcc322949e12e54523124106fc59beffb1",
          "sha256": "e03ceebd25b94f4d6f7c885ce69845684b618fa7dc666fc7b16af8ebe59c0b9b",
          "sha1": "d7cb21f33d6b823583ab592ef4a018d6e61f1a2a",
          "md5": "8eeee8b1dd0f50ede089ae184ebd62fa"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-neoforge-1.21.4-2.1.0-dev-shadow.jar",
          "url": "fastconfigapi-neoforge-1.21.4-2.1.0-dev-shadow.jar",
          "size": 49292,
          "sha512": "74dfb708627a63b2dc974b3988be1b247e976e06e3b2de4c80b3b7f684bf77c2fc43c289a72b6656b793717829f23803e7c49b5f8ed6a4876e9562476d0b1081",
          "sha256": "4f151823bfab7f87efd960a4aa81662c8e996ad7281221b79c7f7006db382550",
          "sha1": "9a2e112949928e0763f11d1dd4f7071ddec31071",
          "md5": "52d580843dc764ec9a5e0e0729864afe"
        }
      ]
    }
  ]
}
