{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.2.jar",
          "url": "fastconfigapi-common-2.0.2.jar",
          "size": 43439,
          "sha512": "9360d8063e89ce5b12288e83507e9b74dfff215bdb2068764b59eaf830d946d61407ee0a7e1214b670ff8616b09c8951e05501327bac78478b724324946a419b",
          "sha256": "e7c25e463bc0f6279a89a56df425932b1c431932eadbbf6d35941d5ee260bc47",
          "sha1": "ea7c41418c8373aab0a7599cfda469546aef8f33",
          "md5": "b02b6d29e81594245c79983a06a6fc00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.0.2.jar",
          "url": "fastconfigapi-common-2.0.2.jar",
          "size": 43439,
          "sha512": "9360d8063e89ce5b12288e83507e9b74dfff215bdb2068764b59eaf830d946d61407ee0a7e1214b670ff8616b09c8951e05501327bac78478b724324946a419b",
          "sha256": "e7c25e463bc0f6279a89a56df425932b1c431932eadbbf6d35941d5ee260bc47",
          "sha1": "ea7c41418c8373aab0a7599cfda469546aef8f33",
          "md5": "b02b6d29e81594245c79983a06a6fc00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.2-sources.jar",
          "url": "fastconfigapi-common-2.0.2-sources.jar",
          "size": 32800,
          "sha512": "0e3e8818072814ea6d57cac1e0ef632559f0d0412a7a167534adbabe3e61733386c06c17392e0f686c1a4bfa0ea730976350dfd50b82b30bf194565b6d3b2e7d",
          "sha256": "4ed03004b7a1a5eafc881edafd6e13cea8c354454a9fd4d179dbe8492cb6173f",
          "sha1": "06f9b9f406ac33f25c3c735cb21e4dbc7a7a561c",
          "md5": "04ec4afc8a110b0f7c556022f7ac630a"
        }
      ]
    }
  ]
}
