{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.2.jar",
          "url": "fastconfigapi-common-2.0.2.jar",
          "size": 30503,
          "sha512": "efb387ce4593f5da53799a521e7485fcf5007dc618e0f35306d9469854cb5fa01c0617b8e853a303c73c4c1cd22bead6e418d5b03528f035da3a806ca72288cb",
          "sha256": "a49a3e26f408e6712b7e6b844253dbd7f068f80f4ec18dcc0518955678cad2a9",
          "sha1": "da7928c7c0649e35a32392c750fc61804b55f278",
          "md5": "047c2b8def55d65660a0207c5c685515"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.0.2.jar",
          "url": "fastconfigapi-common-2.0.2.jar",
          "size": 30503,
          "sha512": "efb387ce4593f5da53799a521e7485fcf5007dc618e0f35306d9469854cb5fa01c0617b8e853a303c73c4c1cd22bead6e418d5b03528f035da3a806ca72288cb",
          "sha256": "a49a3e26f408e6712b7e6b844253dbd7f068f80f4ec18dcc0518955678cad2a9",
          "sha1": "da7928c7c0649e35a32392c750fc61804b55f278",
          "md5": "047c2b8def55d65660a0207c5c685515"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.2-sources.jar",
          "url": "fastconfigapi-common-2.0.2-sources.jar",
          "size": 19809,
          "sha512": "b25f82008e5756ab8f1955e4044320bf4dfd2cf0ca435dabc67582a1c18a3d2c90812e5ceeda6a6071f679d0f69c02afa3f11a928012aa9a1941b39e0199358a",
          "sha256": "bd63443c7446841fb3d63aa229c43008c9fc19ab992ed65222ee8c1da3b3251d",
          "sha1": "7af5a3d23e8f1ec074f39e225a306db34dacb5df",
          "md5": "5c5a6f792110329f36933594dbe45707"
        }
      ]
    }
  ]
}
