{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-forge",
    "version": "1.20.1-2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-forge",
          "version": {
            "requires": "1.20.1-1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.1.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.1.jar",
          "size": 276634,
          "sha512": "3ac55048050e83140f41613a652eeaeb513192265287b7aa35fd15539f013ce63cdcacec4964bccb40c16b9b33371db96764ca00ac6e7aaa2d417d18fac42e6f",
          "sha256": "f9a2fec78ae5a0115a5d34a3dd75c5609722fe3f0b13026e313c0af09d2eeb16",
          "sha1": "3a31475a2372ef076fe2afba984a6a12166c23b6",
          "md5": "44ae71d9e74a4d1418d58e79b9544c03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "infinituum.void_lib",
          "module": "void_lib-forge",
          "version": {
            "requires": "1.20.1-1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.1.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.1.jar",
          "size": 276634,
          "sha512": "3ac55048050e83140f41613a652eeaeb513192265287b7aa35fd15539f013ce63cdcacec4964bccb40c16b9b33371db96764ca00ac6e7aaa2d417d18fac42e6f",
          "sha256": "f9a2fec78ae5a0115a5d34a3dd75c5609722fe3f0b13026e313c0af09d2eeb16",
          "sha1": "3a31475a2372ef076fe2afba984a6a12166c23b6",
          "md5": "44ae71d9e74a4d1418d58e79b9544c03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.1-sources.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.1-sources.jar",
          "size": 4681,
          "sha512": "6e586a536c12568b2e47fae51b93197e757991b215dd9bc5d5c8a6977bce3a25aa1b96e30b5f7df65a7109c6d5db3ebbcefe70ee2fcfd868f1c9cedf0c07bdf3",
          "sha256": "758d61dd645b3a922b1888baf9c375fa88f5b993d288d64526134ff26b12514f",
          "sha1": "f172f2c8879a1640304977f110e8a3c7916cc34d",
          "md5": "308ad4827d2a02c2e1d27fa2e4fe3a56"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-forge-1.20.1-2.0.1-dev-shadow.jar",
          "url": "fastconfigapi-forge-1.20.1-2.0.1-dev-shadow.jar",
          "size": 35040,
          "sha512": "1a799aec9171e36d29be8937f4d520fc292cb3fa04b2d3c558112960c254290ce367fb2ed270d420406d90642f3b2f626f7897ec860eae6bbf91b6fdf0d9ea0a",
          "sha256": "1aae3dd0b94f5d519a76180e21e34064ba7e1e2271408391e1a785d927c18abb",
          "sha1": "2dae186c0389da431826a0e6a0cc9c85ca0eed04",
          "md5": "364dae968550d2d998c8f6f5412504e1"
        }
      ]
    }
  ]
}
