{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.1.jar",
          "url": "fastconfigapi-common-2.1.1.jar",
          "size": 41797,
          "sha512": "e0352cba3c4b97545c45bbba2390336b55630c31ab8435d4812f18fbd7b5418672a84e46c9369cbca298fd81f5cab4fc5c377fe2c799d979994f5c569b8f4fef",
          "sha256": "601ba99c49f564b1aac244252548a59d32ef1edad394b236c5ed68438115d465",
          "sha1": "c4ce31e3308ea9d5fd17eec2450c6ad876968952",
          "md5": "958ef82c4f4063173886cb3e1d82e0fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.1.1.jar",
          "url": "fastconfigapi-common-2.1.1.jar",
          "size": 41797,
          "sha512": "e0352cba3c4b97545c45bbba2390336b55630c31ab8435d4812f18fbd7b5418672a84e46c9369cbca298fd81f5cab4fc5c377fe2c799d979994f5c569b8f4fef",
          "sha256": "601ba99c49f564b1aac244252548a59d32ef1edad394b236c5ed68438115d465",
          "sha1": "c4ce31e3308ea9d5fd17eec2450c6ad876968952",
          "md5": "958ef82c4f4063173886cb3e1d82e0fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.1.1-sources.jar",
          "url": "fastconfigapi-common-2.1.1-sources.jar",
          "size": 31231,
          "sha512": "b7298fd5e4f652da7bd566a6fa27748b07d2dbab5d223584fcfa51522310d952331e0eb9189a4fab8f321a637e2ab6e06b1b83404699c4449ba91aac875171c9",
          "sha256": "64fda2c65d116af0c2e4939002a6c942ea2adcffdcbfce48eabc51f4935aee19",
          "sha1": "ea2984e236efb252b7a94c5a9bb6d2e713aa8530",
          "md5": "3f75e3b8a4d8fc6fb746dd4828f8abcc"
        }
      ]
    }
  ]
}
