{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.6.jar",
          "url": "fastconfigapi-common-2.0.6.jar",
          "size": 43712,
          "sha512": "85123186fa2214cdd15129a87b8031fc01e665afc0068637fe67c7e6ea8e64689b8647fde2809554e2830de3b225eb5e34e26a2d012e17a4507d162c8145a359",
          "sha256": "ff9bd24e3a3718512f114cb256660ad588bb2c695853a892a60889b5fc731e09",
          "sha1": "c7031575e30d77baff9e02ecf800436cece1f87c",
          "md5": "00ed665c750c482d17217a8781c8936c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.0.6.jar",
          "url": "fastconfigapi-common-2.0.6.jar",
          "size": 43712,
          "sha512": "85123186fa2214cdd15129a87b8031fc01e665afc0068637fe67c7e6ea8e64689b8647fde2809554e2830de3b225eb5e34e26a2d012e17a4507d162c8145a359",
          "sha256": "ff9bd24e3a3718512f114cb256660ad588bb2c695853a892a60889b5fc731e09",
          "sha1": "c7031575e30d77baff9e02ecf800436cece1f87c",
          "md5": "00ed665c750c482d17217a8781c8936c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.6-sources.jar",
          "url": "fastconfigapi-common-2.0.6-sources.jar",
          "size": 32912,
          "sha512": "e2b7599e0c19ee2c1b859d638efeb6707aa37565239ec5a8a433e0f82e545efb5b6dfcdd508dfc3edd6ad947ea2f8a9509a69cd5550f81e7a5f1c3f53bd797e4",
          "sha256": "4f8ae9f3f2842939d7f6c6a0401d1fe83f1ae6a28f963e8a5057d03c73f27c2c",
          "sha1": "8aec10150e51525c12adae7004e2a72566968e24",
          "md5": "bf88ea3649f466b8d454364046c1a22b"
        }
      ]
    }
  ]
}
