{
  "formatVersion": "1.1",
  "component": {
    "group": "infinituum.fastconfigapi",
    "module": "fastconfigapi-common",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.6.jar",
          "url": "fastconfigapi-common-2.0.6.jar",
          "size": 48026,
          "sha512": "d33d7cdb06443c7ea42712eb2bb3472949fa855df5744a9dc9374d7db004ee1fc9414585f2809db764c2ffee233d3028a6e238dd5a50aa4d5a69d518d692ce57",
          "sha256": "2e7611b4102fb9d8d2fb455e56ed90eb73f7b5791f8fc7b7135a0cda620f0e2b",
          "sha1": "5e66e1b18bd0a9d6a2eb14ac6650ce448f154f0e",
          "md5": "eb2bb157f756abb319eb2750ad5b925f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "fastconfigapi-common-2.0.6.jar",
          "url": "fastconfigapi-common-2.0.6.jar",
          "size": 48026,
          "sha512": "d33d7cdb06443c7ea42712eb2bb3472949fa855df5744a9dc9374d7db004ee1fc9414585f2809db764c2ffee233d3028a6e238dd5a50aa4d5a69d518d692ce57",
          "sha256": "2e7611b4102fb9d8d2fb455e56ed90eb73f7b5791f8fc7b7135a0cda620f0e2b",
          "sha1": "5e66e1b18bd0a9d6a2eb14ac6650ce448f154f0e",
          "md5": "eb2bb157f756abb319eb2750ad5b925f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastconfigapi-common-2.0.6-sources.jar",
          "url": "fastconfigapi-common-2.0.6-sources.jar",
          "size": 38719,
          "sha512": "bd1b6dfb28c8218d20ae08f70a3d8a9909d09847f75447ebf33d90860341f1805b2113e56dc6d591c1fcd1a2784d41b276cbb7b411729e7623f5c6d2db380f20",
          "sha256": "eaa4a9e2426beee93820eba3c80d0d27f75d5f619a4f3114cf1c39a216ef663d",
          "sha1": "1f2437739f2c8e7a520e03b41ed70b778cbad23f",
          "md5": "2fd52380b223b3100be0f78dde3cac07"
        }
      ]
    }
  ]
}
